export const questions = [
  "What is the time complexity of merge sort?",
  "Explain how binary search works.",
  "What is a hash table, and what are its typical operations?",
  "Describe the difference between a stack and a queue.",
  "What is the purpose of using a heap?",
  "How does depth-first search differ from breadth-first search?",
  "What is the time complexity of inserting an element in a binary search tree?",
  "Explain what dynamic programming is.",
  "What does memoization solve in recursive algorithms?",
  "When would you choose a linked list over an array?",
  "What is the sliding window technique used for?",
  "Describe how the two-pointer technique works.",
  "What is a graph, and how is it represented in code?",
  "How do adjacency matrices differ from adjacency lists?",
  "What is a trie, and where is it commonly used?",
  "How does a priority queue differ from a regular queue?",
  "What are the differences between quicksort and mergesort?",
  "How do you detect a cycle in a linked list?",
  "What problem does a disjoint set (union-find) solve?",
  "Explain the concept of topological sorting in graphs."
];
